#!/usr/bin/env bash

mullvad=$(nmcli con show --active | grep mullvad)
work=$(nmcli con show --active | grep vpn)

if [ "$mullvad" != "" ]; then
    if [ "$1" == "--switch" ]; then
        mullvad disconnect;
        if [ "$2" == "-o" ]; then # o stands for output. Just for the sake of debugging
            nmcli con up id "Work VPN";
        else
            nmcli con up id "Work VPN" >> /dev/null;
        fi
        echo "Work";
    else
        echo "Mullvad"
    fi
elif [ "$work" != "" ]; then
    if [ "$1" == "--switch" ]; then
        if [ "$2" == "-o" ]; then
            nmcli con down id "Work VPN";
        else
            nmcli con down id "Work VPN" >> /dev/null;
        fi
        mullvad connect;
        echo "Mullvad";
    else
        echo "Work";
    fi
else
    echo "None";
fi
